import type { Metadata } from "next";
import { Geist, Geist_Mono, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/usetheme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const BricolageFont = Bricolage_Grotesque({ 
  subsets: ['latin'], 
  weight: ['400', '500', '700'], 
  display: 'swap', 
  variable: '--font-bricolage' 
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${BricolageFont.variable}`}>
        <body className="bg-background font-sans text-foreground transition-colors duration-300">
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
